import os
import sys

from wq_environment import *

Import('env')

cwd = Dir('.').srcnode().abspath
chip = WQTargetConfig.get_target_chip()
core = WQTargetConfig.get_target_core()
memory = WQTargetConfig.get_target_memory()

include_dir = []
include_dir.append(os.path.join(cwd, chip, 'memory'))
include_dir.append(os.path.join(cwd, chip, 'memory', memory))

# Register
include_dir.append(os.path.join(cwd, chip, 'regs'))

# Chip config
include_dir.append(os.path.join(cwd, chip, 'chip'))

# board config
include_dir.append(os.path.join(cwd, chip, 'board'))

# common header
include_dir.append(os.path.join(cwd, 'common', 'regs'))

env.Append(CPPPATH = include_dir)

Return([])
