import os
import sys

from wq_tools import *
from wq_modules import *
from wq_environment import *

Import('env')

cwd = Dir('.').srcnode().abspath

sources = []
sources.extend(Glob('*.c'))
sources.extend(Glob(os.path.join('**', '*.c')))

pub_inc = [cwd]
pri_inc = []
defines = []
flags = []
libs = []

mod = WQModule('customer', sources, env, pri_inc=pri_inc, pub_inc=pub_inc, defines=defines, flags=flags, libs=libs)

Return('mod')
