import os
import sys

from wq_environment import *

Import('env')

project = WQTargetConfig.get_target_project()
core = WQTargetConfig.get_target_core()

cwd = Dir('.').srcnode().abspath
subdir = [
    os.path.join(cwd, 'common'),
]

env.Append(CPPPATH = subdir)

sources = []
sources.extend(SConscript(os.path.join(project, core, 'SConscript'), {"env": env}))

Return('sources')
