import os
import sys

from wq_tools import *
from wq_modules import *
from wq_environment import *

Import('env')

libname = 'mic_dump'

cwd = Dir('.').srcnode().abspath
core = WQTargetConfig.get_target_core()

sources = Glob(os.path.join('src', '*.c'))

env.Append(CPPPATH = os.path.join(cwd, 'inc'))

mod = WQModule(libname, sources, env)

Return('mod')
