/****************************************************************************

Copyright(c) 2020 by WuQi Technologies. ALL RIGHTS RESERVED.

This Information is proprietary to WuQi Technologies and MAY NOT
be copied by any method or incorporated into another program without
the express written consent of WuQi. This Information or any portion
thereof remains the property of WuQi. The Information contained herein
is believed to be accurate and WuQi assumes no responsibility or
liability for its use in any way and conveys no license or title under
any patent or copyright and makes no representation or warranty that this
Information is free from patent or copyright infringement.

****************************************************************************/

#ifndef DRIVER_NON_OS_IRQ_H
#define DRIVER_NON_OS_IRQ_H

#include "chip_irq_vector.h"
#include "iot_irq.h"

const uint8_t irq_int_priority[CHIP_IRQ_VECTOR_MAX] __attribute__((section(".data.irq_int_priority"))) = {
    [VAD_TDVAD_INT]                 = IOT_INTR_PRI_3,
    [WDG0_TIMEOUT_INT]              = IOT_INTR_PRI_7,
    [RTC_TMR0_INT1]                 = IOT_INTR_PRI_3,
    [RTC_TMR0_INT0]                 = IOT_INTR_PRI_3,
    [GTMR0_INT]                     = IOT_INTR_PRI_3,
    [GPIO_INT]                      = IOT_INTR_PRI_3,
    [ASRC1_INT]                     = IOT_INTR_PRI_3,
    [GPIO_WAKEUP]                   = IOT_INTR_PRI_3,
    [VAD_GMM_INT]                   = IOT_INTR_PRI_3,
    [I2C1_INT]                      = IOT_INTR_PRI_3,
    [I2C0_INT]                      = IOT_INTR_PRI_3,
    [DIG_RTC_TIMER_INT0_VLD]        = IOT_INTR_PRI_3,
    [DIG_RTC_TIMER_INT1_VLD]        = IOT_INTR_PRI_3,
    [GPIO_DEB_INT0]                 = IOT_INTR_PRI_3,
    [GPIO_DEB_INT1]                 = IOT_INTR_PRI_3,
    [GPIO_DEB_INT2]                 = IOT_INTR_PRI_3,
    [GPIO_DEB_INT3]                 = IOT_INTR_PRI_3,
    [UART0_INT]                     = IOT_INTR_PRI_3,
    [UART1_INT]                     = IOT_INTR_PRI_3,
    [MADC_INT]                      = IOT_INTR_PRI_3,
    [WDG0_INT]                      = IOT_INTR_PRI_3,
    [MAILBOX0_INT0]                 = IOT_INTR_PRI_3,
    [MAILBOX0_INT1]                 = IOT_INTR_PRI_3,
    [MAILBOX0_INT2]                 = IOT_INTR_PRI_3,
    [MAILBOX0_INT3]                 = IOT_INTR_PRI_3,
    [MAILBOX0_INT4]                 = IOT_INTR_PRI_3,
    [MAILBOX0_INT5]                 = IOT_INTR_PRI_3,
    [ASRC0_INT]                     = IOT_INTR_PRI_3,
    [BT_PD_EARLY_WAKEUP_BY_BT_TMR]  = IOT_INTR_PRI_3,
    [VAD_BUF_INT]                   = IOT_INTR_PRI_3,
    [SPI_M1_INT]                    = IOT_INTR_PRI_3,
    [SPI_M0_INT]                    = IOT_INTR_PRI_3,
    [TK_INT]                        = IOT_INTR_PRI_3,
    [CHARGER_ON_FLAG_INT]           = IOT_INTR_PRI_3,
    [FIREWALL_MTX_MIX_INT]          = IOT_INTR_PRI_3,
    [DMA0_INT0]                     = IOT_INTR_PRI_3,
    [DMA0_INT1]                     = IOT_INTR_PRI_3,
    [DMA0_INT2]                     = IOT_INTR_PRI_3,
    [DMA0_INT3]                     = IOT_INTR_PRI_3,
    [PMM_GPIO_DEB_INT_ALL]          = IOT_INTR_PRI_3,
    [PMM_BOD_INT]                   = IOT_INTR_PRI_3,
    [DIG_GPIO_WAKEUP]               = IOT_INTR_PRI_3,
    [ADA_INT]                       = IOT_INTR_PRI_3,
    [PMM_LEDC_INT]                  = IOT_INTR_PRI_3,
    [PMM_WDG_DTOP_INT]              = IOT_INTR_PRI_3,
    [PMM_WDG_DTOP_TIMEOUT_INT]      = IOT_INTR_PRI_7,
    [ANC_INT]                       = IOT_INTR_PRI_3,
    [PMM_GPIO_INT]                  = IOT_INTR_PRI_3,
    [DM_INT]                        = IOT_INTR_PRI_6,
    [BT_INT]                        = IOT_INTR_PRI_3,
    [BLE_INT]                       = IOT_INTR_PRI_3,
    [BLE_ISO_INT]                   = IOT_INTR_PRI_3,
    [BT_RAW_INT]                    = IOT_INTR_PRI_3,
    [PHY_INT_0]                     = IOT_INTR_PRI_3,
    [PHY_INT_1]                     = IOT_INTR_PRI_3,
    [BT_NAK_INT]                    = IOT_INTR_PRI_3,
    [DM_TIMESTAMP_TARG3_INT]        = IOT_INTR_PRI_6,
    [DM_FIFO_INT]                   = IOT_INTR_PRI_6,
    [DM_ERROR_INT]                  = IOT_INTR_PRI_6,
    [DM_FINETGT_INT]                = IOT_INTR_PRI_6,
    [DM_TIMESTAMP_TARG2_INT]        = IOT_INTR_PRI_6,
    [DM_TIMESTAMP_TARG1_INT]        = IOT_INTR_PRI_6,
    [DM_CRYPT_INT]                  = IOT_INTR_PRI_6,
    [DM_SLP_INT]                    = IOT_INTR_PRI_6,
    [DM_HSLOT_INT]                  = IOT_INTR_PRI_6,
    [DM_SW_INT]                     = IOT_INTR_PRI_6,
    [BT_ERROR_INT]                  = IOT_INTR_PRI_3,
    [BT_AUDIO2_INT]                 = IOT_INTR_PRI_3,
    [BT_AUDIO1_INT]                 = IOT_INTR_PRI_3,
    [BT_AUDIO0_INT]                 = IOT_INTR_PRI_3,
    [BLE_HOP_INT]                   = IOT_INTR_PRI_3,
    [BLE_ERROR_INT]                 = IOT_INTR_PRI_3,
    [BLT_ISO_INT_0]                 = IOT_INTR_PRI_3,
    [BLT_ISO_INT_1]                 = IOT_INTR_PRI_3,
    [BLT_ISO_INT_2]                 = IOT_INTR_PRI_3,
    [BLT_ISO_INT_3]                 = IOT_INTR_PRI_3,
    [BLT_ISO_INT_4]                 = IOT_INTR_PRI_3,
    [BLT_ISO_INT_5]                 = IOT_INTR_PRI_3,
    [BLT_ISO_INT_6]                 = IOT_INTR_PRI_3,
    [BLT_ISO_INT_7]                 = IOT_INTR_PRI_3,
    [WDG1_INT]                      = IOT_INTR_PRI_3,
    [WDG1_TIMEOUT_INT]              = IOT_INTR_PRI_7,
    [RTC_TMR1_INT1]                 = IOT_INTR_PRI_3,
    [RTC_TMR1_INT0]                 = IOT_INTR_PRI_3,
    [GTMR1_INT]                     = IOT_INTR_PRI_3,
    [RTC_MON_INT]                   = IOT_INTR_PRI_5,
    [MAILBOX1_INT0]                 = IOT_INTR_PRI_3,
    [MAILBOX1_INT1]                 = IOT_INTR_PRI_3,
    [DMA1_INT0]                     = IOT_INTR_PRI_3,
    [DMA1_INT1]                     = IOT_INTR_PRI_3,
    [DMA1_INT2]                     = IOT_INTR_PRI_3,
    [DMA1_INT3]                     = IOT_INTR_PRI_3,
    [WDG2_INT]                      = IOT_INTR_PRI_3,
    [WDG2_TIMEOUT_INT]              = IOT_INTR_PRI_7,
    [BTR_TRIGGER_HW_ERR_INT]        = IOT_INTR_PRI_3,
    [BCP_FIREWALL_INT]              = IOT_INTR_PRI_3,
    [WDG3_INT]                      = IOT_INTR_PRI_3,
    [WDG3_TIMEOUT_INT]              = IOT_INTR_PRI_7,
    [RTC_TMR2_INT1]                 = IOT_INTR_PRI_3,
    [RTC_TMR2_INT0]                 = IOT_INTR_PRI_3,
    [GTMR2_INT]                     = IOT_INTR_PRI_3,
    [PMC_INT]                       = IOT_INTR_PRI_3,
    [PFATALERROR_INT]               = IOT_INTR_PRI_3,
    [DOUBLEEXCEPTIONERROR_INT]      = IOT_INTR_PRI_3,
    [DMA2_INT0]                     = IOT_INTR_PRI_3,
    [DMA2_INT1]                     = IOT_INTR_PRI_3,
    [DMA2_INT2]                     = IOT_INTR_PRI_3,
    [DMA2_INT3]                     = IOT_INTR_PRI_3,
    [ACP_FIREWALL_INT]              = IOT_INTR_PRI_3,
    [WIC_WAKEN_UP_INT_BT2AUD]       = IOT_INTR_PRI_3,
    [WIC_WAKEN_UP_INT_DCORE2AUD]    = IOT_INTR_PRI_3,
    [WIC_QUERY_INT_AUD2BT]          = IOT_INTR_PRI_3,
    [WIC_QUERY_INT_AUD2DCORE]       = IOT_INTR_PRI_3,
    [SMC_CACHE_MON_ERR_INT]         = IOT_INTR_PRI_3,
    [WIC_QUERY_INT_DCORE2AUD]       = IOT_INTR_PRI_3,
    [WIC_QUERY_INT_DCORE2BT]        = IOT_INTR_PRI_3,
    [WIC_WAKEN_UP_INT_AUD2DCORE]    = IOT_INTR_PRI_3,
    [WIC_WAKEN_UP_INT_BT2DCORE]     = IOT_INTR_PRI_3,
    [WIC_WAKEN_UP_INT_AUD2BT]       = IOT_INTR_PRI_3,
    [WIC_WAKEN_UP_INT_DCORE2BT]     = IOT_INTR_PRI_3,
    [WIC_QUERY_INT_BT2AUD]          = IOT_INTR_PRI_3,
    [WIC_QUERY_INT_BT2DCORE]        = IOT_INTR_PRI_3,
    [EQ_DONE_INT]                   = IOT_INTR_PRI_3,
    [FFT_INT]                       = IOT_INTR_PRI_3,
    [SDM_DAC_REG_INT]               = IOT_INTR_PRI_3,
    [AUDIO_INF_REG_INT]             = IOT_INTR_PRI_3,
    [VAD_TDVAD_DBG_INT]             = IOT_INTR_PRI_3,
    [WAKEUP_INT]                    = IOT_INTR_PRI_7,
};

#endif
