import os
import sys

from wq_modules import *
from wq_environment import *

Import('env')

# tws entry
app =  WQTargetConfig.get_target_app()
tws_entry =  WQTargetConfig.get_target_options().get('entry')
assert app and tws_entry

libname = app + tws_entry + 'app'

cwd = Dir('.').srcnode().abspath
include_dir = []
include_dir.append(cwd)
include_dir.append(os.path.join(cwd, 'common'))
include_dir.append(os.path.join(cwd, tws_entry))

env.Append(CPPPATH = include_dir)

sources = []
sources.extend(Glob(os.path.join(tws_entry, '*.c')))
sources.extend(Glob(os.path.join(tws_entry, '**', '*.c')))
sources.extend(Glob(os.path.join(tws_entry, '**', '*.co')))
sources.extend(Glob(os.path.join(tws_entry, '**', '*.S')))
sources.append(Glob(os.path.join('common', '*.c')))

mod = WQModule(libname, sources, env)

Return('mod')
