import os
import sys

from wq_tools import *
from wq_modules import *
from wq_environment import *

Import('env')

libname = 'iot_debug'

cwd = Dir('.').srcnode().abspath
core = WQTargetConfig.get_target_core()

sources = []

sources.append(Glob(os.path.join('src', 'iot_debug.c')))

if WQTargetConfig.get_use_os() == 'freertos_10_2_1':
    sources.append(os.path.join('src', 'iot_coredump.c'))
env.Append(CPPPATH = os.path.join(cwd, 'inc'))

mod = WQModule(libname, sources, env)

Return('mod')
