import os
import sys

from wq_tools import *
from wq_modules import *
from wq_environment import *

Import('env')

libname = 'suspend_sched'

cwd = Dir('.').srcnode().abspath
core = WQTargetConfig.get_target_core()

sources = Glob(os.path.join('src', '*.c'))
if WQTargetConfig.get_build_type() in ['rom_lib']:
    sources = wq_rom_lib_src(sources, ['inc'], env)
else:
    env.Append(CPPPATH = os.path.join(cwd, 'inc'))

mod = WQModule(libname, sources, env)

Return('mod')
