import os
import sys

from wq_tools import *
from wq_modules import *
from wq_environment import *

Import('env')

libname = 'battery'

cwd = Dir('.').srcnode().abspath

sources = []

if WQTargetConfig.get_target_platform() == 'fpga' :
    sources.extend(Glob(os.path.join('src', 'dummy_battery', '*.c')))
else :
    sources.extend(Glob(os.path.join('src', 'battery', '*.c')))

env.Append(CPPPATH = os.path.join(cwd, 'inc'))

mod = WQModule(libname, sources, env)

Return('mod')
