/****************************************************************************

Copyright(c) 2020 by WuQi Technologies. ALL RIGHTS RESERVED.

This Information is proprietary to WuQi Technologies and MAY NOT
be copied by any method or incorporated into another program without
the express written consent of WuQi. This Information or any portion
thereof remains the property of WuQi. The Information contained herein
is believed to be accurate and WuQi assumes no responsibility or
liability for its use in any way and conveys no license or title under
any patent or copyright and makes no representation or warranty that this
Information is free from patent or copyright infringement.

****************************************************************************/

/**
 * @addtogroup APP
 * @{
 */

/**
 * @addtogroup APP_EVT
 * @{
 * This section introduces the APP EVT module's enum, structure, functions and how to use this module.
 */

#ifndef _APP_EVT_H_
#define _APP_EVT_H_
#include "types.h"
#include "userapp_dbglog.h"

#define DBGLOG_EVT_DBG(fmt, ...) DBGLOG_USER_APP_INFO("[evt] " fmt, ##__VA_ARGS__)
#define DBGLOG_EVT_ERR(fmt, ...) DBGLOG_USER_APP_ERROR("[evt] " fmt, ##__VA_ARGS__)

#define EVTUSR_BASE 1000
#define EVTSYS_BASE 8000

/** @defgroup app_evt_enum Enum
 * @{
 */

/** @brief events generated by button or sensors */
typedef enum {
    EVTUSR_POWER_ON = EVTUSR_BASE,
    EVTUSR_POWER_OFF,
    EVTUSR_FACTORY_RESET,
    EVTUSR_CLEAR_PDL,
    EVTUSR_START_WWS_PAIR,
    EVTUSR_WWS_ROLE_SWITCH,
    EVTUSR_ENTER_PAIRING,
    EVTUSR_CANCEL_PAIRING,
    EVTUSR_CONNECT_LAST,
    EVTUSR_VOICE_TRANSFER_TOGGLE,
    EVTUSR_VOICE_RECOGNITION_TOGGLE,
    EVTUSR_REDIAL_LAST,
    EVTUSR_ANSWER,
    EVTUSR_REJECT,
    EVTUSR_HANGUP,
    EVTUSR_THREE_WAY_REJECT_WAITING,
    EVTUSR_THREE_WAY_RELEASE_ACTIVE_ACCEPT_HELD_WAITING,
    EVTUSR_THREE_WAY_HOLD_ACTIVE_ACCEPT_HELD_WAITING,
    EVTUSR_AUDIO_PROMPT_LANGUAGE_TOGGLE,
    EVTUSR_MUSIC_PLAY_PAUSE,
    EVTUSR_MUSIC_PLAY,
    EVTUSR_MUSIC_PAUSE,
    EVTUSR_MUSIC_STOP,
    EVTUSR_MUSIC_FORWARD,
    EVTUSR_MUSIC_BACKWARD,
    EVTUSR_VOLUME_UP,
    EVTUSR_VOLUME_DOWN,
    EVTUSR_MIC_MUTE,
    EVTUSR_MIC_UNMUTE,
    EVTUSR_MIC_MUTE_TOGGLE,
    EVTUSR_SPK_MUTE,
    EVTUSR_SPK_UNMUTE,
    EVTUSR_SPK_MUTE_TOGGLE,
    EVTUSR_USER_EQ_ON,
    EVTUSR_USER_EQ_OFF,
    EVTUSR_USER_EQ_TOGGLE,
    /* anc, normal, transparent */
    EVTUSR_LISTEN_MODE_TOGGLE,
    EVTUSR_ENTER_FACTORY_TEST_MODE,
    EVTUSR_ENTER_OTA_MODE,
    EVTUSR_ENTER_AUDIO_TEST_MODE,
    EVTUSR_CUSTOM_1,
    EVTUSR_CUSTOM_2,
    EVTUSR_CUSTOM_3,
    EVTUSR_CUSTOM_4,
    EVTUSR_CUSTOM_5,
    EVTUSR_CUSTOM_6,
    EVTUSR_CUSTOM_7,
    EVTUSR_CUSTOM_8,
    EVTUSR_GAME_MODE_TOGGLE,
    EVTUSR_FACTORY_RESET_KEEP_WWS,
    EVTUSR_ENTER_DUT_MODE,
    EVTUSR_USER_INEAR_ENABLE_TOGGLE,
    EVTUSR_VOICE_RECOGNITION_ACTIVATE,
    EVTUSR_VOICE_RECOGNITION_DEACTIVATE,
    EVTUSR_ENTER_SHIPPING_MODE,
    /* last user event */
    EVTUSR_LAST
} app_usr_evt_t;

/** @brief events generated by internal, not by button or sensors */
typedef enum {
    EVTSYS_BT_INITED = EVTSYS_BASE,
    EVTSYS_STATE_CHANGED,
    EVTSYS_CONNECTED,
    EVTSYS_DISCONNECTED,
    EVTSYS_LINK_LOSS,
    EVTSYS_SCOLINK_OPEN,
    EVTSYS_SCOLINK_CLOSE,
    EVTSYS_VOICE_RECOGNITION_START,
    EVTSYS_VOICE_RECOGNITION_STOP,
    EVTSYS_RING,
    EVTSYS_CALL_END,
    EVTSYS_WWS_CONNECTED,
    EVTSYS_WWS_DISCONNECTED,
    EVTSYS_WWS_ROLE_SWITCH,
    EVTSYS_CHARGE_COMPLETE,
    EVTSYS_CHARGE_CONNECTED,
    EVTSYS_CHARGE_DISCONNECTED,
    EVTSYS_BATTERY_LOW,
    EVTSYS_BATTERY_LEVEL_CHANGED,
    EVTSYS_VOLUME_MAX,
    EVTSYS_VOLUME_MIN,
    EVTSYS_MUSIC_VOLUME_CHANGED,
    EVTSYS_CALL_VOLUME_CHANGED,
    EVTSYS_CMC_BOX_OPEN,    //charger box open cmd
    EVTSYS_CMC_BOX_CLOSE,   //charger box close cmd
    EVTSYS_CMC_LONG_3S,     //charger box long press 3s
    EVTSYS_CMC_LONG_10S,    //charger box long press 10s
    EVTSYS_CMC_LONG_20S,    //charger box long press 20s
    EVTSYS_WWS_PAIRED,
    EVTSYS_WWS_PAIR_FAILED,
    EVTSYS_IN_EAR,
    EVTSYS_OUT_OF_EAR,
    EVTSYS_LISTEN_MODE_NORMAL,
    EVTSYS_LISTEN_MODE_ANC,
    EVTSYS_LISTEN_MODE_TRANSPARENT,
    EVTSYS_BT_POWER_ON,
    EVTSYS_BT_POWER_OFF,
    EVTSYS_ENTER_PAIRING,
    EVTSYS_BUTTON_PRESS,
    EVTSYS_INEAR_ENABLE,
    EVTSYS_INEAR_DISABLE,
    EVTSYS_CUSTOM_1,
    EVTSYS_CUSTOM_2,
    EVTSYS_CUSTOM_3,
    EVTSYS_CUSTOM_4,
    EVTSYS_CUSTOM_5,
    EVTSYS_CUSTOM_6,
    EVTSYS_CUSTOM_7,
    EVTSYS_CUSTOM_8,
    EVTSYS_POWER_ON_RECONNECT_FAILED,
    EVTSYS_LINK_LOSS_RECONNECT_FAILED,
    EVTSYS_FACTORY_RESET_DONE,
    EVTSYS_BOX_CMD_POWER_OFF,
    EVTSYS_BOX_CMD_REBOOT,
    EVTSYS_BOX_CMD_BT_DISABLE,
    EVTSYS_AUTO_POWER_OFF,
    EVTSYS_GAME_MODE_ON,
    EVTSYS_GAME_MODE_OFF,
    EVTSYS_BAT_LOW_POWER_OFF,
    EVTSYS_BUTTON_SINGLE,
    EVTSYS_BUTTON_DOUBLE,
    EVTSYS_BUTTON_LONG,
    EVTSYS_BUTTON_VLONG,
    EVTSYS_BUTTON_RELEASE,
    /* last system event */
    EVTSYS_LAST
} app_sys_evt_t;
/**
 * @}
 */

/**
 * @brief init the app event module
 */
void app_evt_init(void);

/**
 * @brief deinit the app event module
 */
void app_evt_deinit(void);

/**
 * @brief send an app event
 *
 * @param evt the event, see EVTUSR_XXX and EVTSYS_XXX for detail
 */
void app_evt_send(uint16_t evt);

/**
 * @brief send an app event with param
 *
 * @param evt  the event, see EVTSYS_XXX for detail
 * @param param pointer to the param
 * @param param_len length of the param
 */
void app_evt_send_with_param(uint16_t evt, void *param, uint16_t param_len);

/**
 * @brief send an app event after a period of time
 *
 * @param evt the event, see EVTUSR_XXX and EVTSYS_XXX for detail
 * @param delay_ms time to delay before send the event, unit: ms
 */
void app_evt_send_delay(uint16_t evt, uint32_t delay_ms);

/**
 * @brief cancel a event, send by app_evt_send_delay
 *
 * @param evt the event, see EVTUSR_XXX and EVTSYS_XXX for detail
 */
void app_evt_cancel(uint16_t evt);

/**
 * @brief private function to handle peer user event
 *
 * @param evt user event from peer
 */
void app_evt_handle_peer_evt(uint16_t evt);

/**
 * @}
 * addtogroup APP_EVT
 */

/**
 * @}
 * addtogroup APP
 */

#endif
