import os
import sys

from wq_tools import *
from wq_modules import *
from wq_environment import *

Import('env')

libname = 'rpc'

cwd = Dir('.').srcnode().abspath
core = WQTargetConfig.get_target_core()

env.Append(CPPPATH = [cwd, os.path.join(cwd, 'dtop')])

mod = WQModule(libname, [], env, libs = libname)

Return('mod')
